# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d5c8da430fd352788fd90ff809acfa9970c6d6430ee874a5adeea68bfd19bc2f8e0ff81e400b7be1f6508003443085dd93258d9c21bc0006ed7bc80b923b173

test:
  secret_key_base: 8c36cbafca30c60177454382c1ce41f8a0e019b28097f2c0282be64c0fde7baaf336a81404411d4463a3999513e17907fcd4f796a12b3a88bda8f03003d87c46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
